require("prototypes.spidertron_mkn1.gun")
require("prototypes.spidertron_mkn1.equipment_grid")
require("prototypes.spidertron_mkn1.entity")
require("prototypes.spidertron_mkn1.item")
require("prototypes.spidertron_mkn1.recipe")
require("prototypes.spidertron_mkn1.technology")

require("prototypes.spidertron_mk0.gun")
require("prototypes.spidertron_mk0.equipment_grid")
require("prototypes.spidertron_mk0.entity")
require("prototypes.spidertron_mk0.item")
require("prototypes.spidertron_mk0.recipe")
require("prototypes.spidertron_mk0.technology")

require("prototypes.spidertron_mk2.gun")
require("prototypes.spidertron_mk2.equipment_grid")
require("prototypes.spidertron_mk2.entity")
require("prototypes.spidertron_mk2.item")
require("prototypes.spidertron_mk2.recipe")
require("prototypes.spidertron_mk2.technology")

require("prototypes.spidertron_mk3.gun")
require("prototypes.spidertron_mk3.equipment_grid")
require("prototypes.spidertron_mk3.entity")
require("prototypes.spidertron_mk3.item")
require("prototypes.spidertron_mk3.recipe")
require("prototypes.spidertron_mk3.technology")

require("change_vanilla_spidertron")