require("prototypes.prototype_spidertron.gun")
require("prototypes.prototype_spidertron.equipment_grid")
require("prototypes.prototype_spidertron.entity")
require("prototypes.prototype_spidertron.item")
require("prototypes.prototype_spidertron.recipe")
require("prototypes.prototype_spidertron.technology")

require("prototypes.spidertron_mkn1.gun")
require("prototypes.spidertron_mkn1.equipment_grid")
require("prototypes.spidertron_mkn1.entity")
require("prototypes.spidertron_mkn1.item")
require("prototypes.spidertron_mkn1.recipe")
require("prototypes.spidertron_mkn1.technology")

require("prototypes.spidertron_mk0.gun")
require("prototypes.spidertron_mk0.equipment_grid")
require("prototypes.spidertron_mk0.entity")
require("prototypes.spidertron_mk0.item")
require("prototypes.spidertron_mk0.recipe")
require("prototypes.spidertron_mk0.technology")

require("prototypes.spidertron_mk2.gun")
require("prototypes.spidertron_mk2.equipment_grid")
require("prototypes.spidertron_mk2.entity")
require("prototypes.spidertron_mk2.item")
require("prototypes.spidertron_mk2.recipe")
require("prototypes.spidertron_mk2.technology")

require("prototypes.spidertron_mk3.gun")
require("prototypes.spidertron_mk3.equipment_grid")
require("prototypes.spidertron_mk3.entity")
require("prototypes.spidertron_mk3.item")
require("prototypes.spidertron_mk3.recipe")
require("prototypes.spidertron_mk3.technology")

require("prototypes.assault_spidertron_mk1.gun")
require("prototypes.assault_spidertron_mk1.equipment_grid")
require("prototypes.assault_spidertron_mk1.entity")
require("prototypes.assault_spidertron_mk1.item")
require("prototypes.assault_spidertron_mk1.recipe")
require("prototypes.assault_spidertron_mk1.technology")

require("prototypes.assault_spidertron_mk2.gun")
require("prototypes.assault_spidertron_mk2.equipment_grid")
require("prototypes.assault_spidertron_mk2.entity")
require("prototypes.assault_spidertron_mk2.item")
require("prototypes.assault_spidertron_mk2.recipe")
require("prototypes.assault_spidertron_mk2.technology")

require("prototypes.bulwark_spidertron_mk1.gun")
require("prototypes.bulwark_spidertron_mk1.equipment_grid")
require("prototypes.bulwark_spidertron_mk1.entity")
require("prototypes.bulwark_spidertron_mk1.item")
require("prototypes.bulwark_spidertron_mk1.recipe")
require("prototypes.bulwark_spidertron_mk1.technology")

require("prototypes.bulwark_spidertron_mk2.gun")
require("prototypes.bulwark_spidertron_mk2.equipment_grid")
require("prototypes.bulwark_spidertron_mk2.entity")
require("prototypes.bulwark_spidertron_mk2.item")
require("prototypes.bulwark_spidertron_mk2.recipe")
require("prototypes.bulwark_spidertron_mk2.technology")

require("prototypes.scout_spidertron_mk1.gun")
require("prototypes.scout_spidertron_mk1.equipment_grid")
require("prototypes.scout_spidertron_mk1.entity")
require("prototypes.scout_spidertron_mk1.item")
require("prototypes.scout_spidertron_mk1.recipe")
require("prototypes.scout_spidertron_mk1.technology")

require("prototypes.scout_spidertron_mk2.gun")
require("prototypes.scout_spidertron_mk2.equipment_grid")
require("prototypes.scout_spidertron_mk2.entity")
require("prototypes.scout_spidertron_mk2.item")
require("prototypes.scout_spidertron_mk2.recipe")
require("prototypes.scout_spidertron_mk2.technology")

require("prototypes.voyage_spidertron_mk1.gun")
require("prototypes.voyage_spidertron_mk1.equipment_grid")
require("prototypes.voyage_spidertron_mk1.entity")
require("prototypes.voyage_spidertron_mk1.item")
require("prototypes.voyage_spidertron_mk1.recipe")
require("prototypes.voyage_spidertron_mk1.technology")

require("prototypes.voyage_spidertron_mk2.gun")
require("prototypes.voyage_spidertron_mk2.equipment_grid")
require("prototypes.voyage_spidertron_mk2.entity")
require("prototypes.voyage_spidertron_mk2.item")
require("prototypes.voyage_spidertron_mk2.recipe")
require("prototypes.voyage_spidertron_mk2.technology")

require("change_vanilla_spidertron")