utils = require("__spidertrontiers-circulardependency__.prototypes.utils")

require("__spidertrontiers-circulardependency__.prototypes.prototype_spidertron.gun")
require("__spidertrontiers-circulardependency__.prototypes.prototype_spidertron.equipment_grid")
require("__spidertrontiers-circulardependency__.prototypes.prototype_spidertron.entity")
require("__spidertrontiers-circulardependency__.prototypes.prototype_spidertron.item")
require("__spidertrontiers-circulardependency__.prototypes.prototype_spidertron.recipe")
require("__spidertrontiers-circulardependency__.prototypes.prototype_spidertron.technology")

require("__spidertrontiers-circulardependency__.prototypes.spidertron_mkn1.gun")
require("__spidertrontiers-circulardependency__.prototypes.spidertron_mkn1.equipment_grid")
require("__spidertrontiers-circulardependency__.prototypes.spidertron_mkn1.entity")
require("__spidertrontiers-circulardependency__.prototypes.spidertron_mkn1.item")
require("__spidertrontiers-circulardependency__.prototypes.spidertron_mkn1.recipe")
require("__spidertrontiers-circulardependency__.prototypes.spidertron_mkn1.technology")

require("__spidertrontiers-circulardependency__.prototypes.spidertron_mk0.gun")
require("__spidertrontiers-circulardependency__.prototypes.spidertron_mk0.equipment_grid")
require("__spidertrontiers-circulardependency__.prototypes.spidertron_mk0.entity")
require("__spidertrontiers-circulardependency__.prototypes.spidertron_mk0.item")
require("__spidertrontiers-circulardependency__.prototypes.spidertron_mk0.recipe")
require("__spidertrontiers-circulardependency__.prototypes.spidertron_mk0.technology")

require("__spidertrontiers-circulardependency__.prototypes.spidertron_mk2.gun")
require("__spidertrontiers-circulardependency__.prototypes.spidertron_mk2.equipment_grid")
require("__spidertrontiers-circulardependency__.prototypes.spidertron_mk2.entity")
require("__spidertrontiers-circulardependency__.prototypes.spidertron_mk2.item")
require("__spidertrontiers-circulardependency__.prototypes.spidertron_mk2.recipe")
require("__spidertrontiers-circulardependency__.prototypes.spidertron_mk2.technology")

require("__spidertrontiers-circulardependency__.prototypes.spidertron_mk3.gun")
require("__spidertrontiers-circulardependency__.prototypes.spidertron_mk3.equipment_grid")
require("__spidertrontiers-circulardependency__.prototypes.spidertron_mk3.entity")
require("__spidertrontiers-circulardependency__.prototypes.spidertron_mk3.item")
require("__spidertrontiers-circulardependency__.prototypes.spidertron_mk3.recipe")
require("__spidertrontiers-circulardependency__.prototypes.spidertron_mk3.technology")

require("__spidertrontiers-circulardependency__.prototypes.assault_spidertron_mk1.gun")
require("__spidertrontiers-circulardependency__.prototypes.assault_spidertron_mk1.equipment_grid")
require("__spidertrontiers-circulardependency__.prototypes.assault_spidertron_mk1.entity")
require("__spidertrontiers-circulardependency__.prototypes.assault_spidertron_mk1.item")
require("__spidertrontiers-circulardependency__.prototypes.assault_spidertron_mk1.recipe")
require("__spidertrontiers-circulardependency__.prototypes.assault_spidertron_mk1.technology")

require("__spidertrontiers-circulardependency__.prototypes.assault_spidertron_mk2.gun")
require("__spidertrontiers-circulardependency__.prototypes.assault_spidertron_mk2.equipment_grid")
require("__spidertrontiers-circulardependency__.prototypes.assault_spidertron_mk2.entity")
require("__spidertrontiers-circulardependency__.prototypes.assault_spidertron_mk2.item")
require("__spidertrontiers-circulardependency__.prototypes.assault_spidertron_mk2.recipe")
require("__spidertrontiers-circulardependency__.prototypes.assault_spidertron_mk2.technology")

require("__spidertrontiers-circulardependency__.prototypes.bulwark_spidertron_mk1.gun")
require("__spidertrontiers-circulardependency__.prototypes.bulwark_spidertron_mk1.equipment_grid")
require("__spidertrontiers-circulardependency__.prototypes.bulwark_spidertron_mk1.entity")
require("__spidertrontiers-circulardependency__.prototypes.bulwark_spidertron_mk1.item")
require("__spidertrontiers-circulardependency__.prototypes.bulwark_spidertron_mk1.recipe")
require("__spidertrontiers-circulardependency__.prototypes.bulwark_spidertron_mk1.technology")

require("__spidertrontiers-circulardependency__.prototypes.bulwark_spidertron_mk2.gun")
require("__spidertrontiers-circulardependency__.prototypes.bulwark_spidertron_mk2.equipment_grid")
require("__spidertrontiers-circulardependency__.prototypes.bulwark_spidertron_mk2.entity")
require("__spidertrontiers-circulardependency__.prototypes.bulwark_spidertron_mk2.item")
require("__spidertrontiers-circulardependency__.prototypes.bulwark_spidertron_mk2.recipe")
require("__spidertrontiers-circulardependency__.prototypes.bulwark_spidertron_mk2.technology")

require("__spidertrontiers-circulardependency__.prototypes.scout_spidertron_mk1.gun")
require("__spidertrontiers-circulardependency__.prototypes.scout_spidertron_mk1.equipment_grid")
require("__spidertrontiers-circulardependency__.prototypes.scout_spidertron_mk1.entity")
require("__spidertrontiers-circulardependency__.prototypes.scout_spidertron_mk1.item")
require("__spidertrontiers-circulardependency__.prototypes.scout_spidertron_mk1.recipe")
require("__spidertrontiers-circulardependency__.prototypes.scout_spidertron_mk1.technology")

require("__spidertrontiers-circulardependency__.prototypes.scout_spidertron_mk2.gun")
require("__spidertrontiers-circulardependency__.prototypes.scout_spidertron_mk2.equipment_grid")
require("__spidertrontiers-circulardependency__.prototypes.scout_spidertron_mk2.entity")
require("__spidertrontiers-circulardependency__.prototypes.scout_spidertron_mk2.item")
require("__spidertrontiers-circulardependency__.prototypes.scout_spidertron_mk2.recipe")
require("__spidertrontiers-circulardependency__.prototypes.scout_spidertron_mk2.technology")

require("__spidertrontiers-circulardependency__.prototypes.voyage_spidertron_mk1.gun")
require("__spidertrontiers-circulardependency__.prototypes.voyage_spidertron_mk1.equipment_grid")
require("__spidertrontiers-circulardependency__.prototypes.voyage_spidertron_mk1.entity")
require("__spidertrontiers-circulardependency__.prototypes.voyage_spidertron_mk1.item")
require("__spidertrontiers-circulardependency__.prototypes.voyage_spidertron_mk1.recipe")
require("__spidertrontiers-circulardependency__.prototypes.voyage_spidertron_mk1.technology")

require("__spidertrontiers-circulardependency__.prototypes.voyage_spidertron_mk2.gun")
require("__spidertrontiers-circulardependency__.prototypes.voyage_spidertron_mk2.equipment_grid")
require("__spidertrontiers-circulardependency__.prototypes.voyage_spidertron_mk2.entity")
require("__spidertrontiers-circulardependency__.prototypes.voyage_spidertron_mk2.item")
require("__spidertrontiers-circulardependency__.prototypes.voyage_spidertron_mk2.recipe")
require("__spidertrontiers-circulardependency__.prototypes.voyage_spidertron_mk2.technology")

require("__spidertrontiers-circulardependency__.change_vanilla_spidertron")

require("__spidertrontiers-circulardependency__.prototypes.spidertron_remote.recipe")
require("__spidertrontiers-circulardependency__.prototypes.spidertron_remote.technology")
